-- MySQL Script generated by MySQL Workbench
-- 02/26/20 10:35:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Schema komus_new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `komus_new` DEFAULT CHARACTER SET utf8 ;
USE `komus_new` ;

-- -----------------------------------------------------
-- Table `komus_new`.`timezone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`timezone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `zone` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komus_new`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`regions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(10) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `subcode` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `timezone_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_regions_timezones1_idx` (`timezone_id` ASC),
  CONSTRAINT `fk_regions_timezones1`
    FOREIGN KEY (`timezone_id`)
    REFERENCES `komus_new`.`timezone` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komus_new`.`groups_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`groups_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `groups` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gru_groupid` (`id` ASC),
  INDEX `gru_userid` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `komus_new`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `firstname` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `lastname` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `gender` ENUM('мужчина', 'женщина', 'не указано') CHARACTER SET 'utf8' NOT NULL DEFAULT 'не указано',
  `salt` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL DEFAULT 'не указано',
  `depass` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL DEFAULT 'не указано',
  `birthdate` DATE NULL DEFAULT NULL,
  `lastvisit` DATETIME NULL DEFAULT NULL,
  `ban` TINYINT(1) NULL DEFAULT NULL,
  `timezone_id` INT(11) NOT NULL,
  `groups_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_password` (`token` ASC),
  INDEX `fk_users_timezones_idx` (`timezone_id` ASC),
  INDEX `fk_users_groups_users1_idx` (`groups_id` ASC),
  UNIQUE INDEX `user_login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `komus_new`.`groups_users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_timezones`
    FOREIGN KEY (`timezone_id`)
    REFERENCES `komus_new`.`timezone` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `komus_new`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`contacts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `creation_time` DATETIME NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `organization` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `fio` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `subcategory` VARCHAR(255) NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `allow_call` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
  `comment` TEXT CHARACTER SET 'cp1251' NULL DEFAULT NULL,
  `regions_id` INT(11) NOT NULL,
  `users_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_regions1_idx` (`regions_id` ASC),
  INDEX `fk_contacts_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_contacts_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `komus_new`.`regions` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `komus_new`.`users` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `komus_new`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`calls` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `begin_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `recall_time` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `contacts_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calls_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_calls_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `komus_new`.`contacts` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `komus_new`.`maillog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komus_new`.`maillog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `log` TEXT NOT NULL,
  `contacts_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maillog_contacts1_idx` (`contacts_id` ASC),
  CONSTRAINT `fk_maillog_contacts1`
    FOREIGN KEY (`contacts_id`)
    REFERENCES `komus_new`.`contacts` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
PACK_KEYS = 0
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
